name: PersonioAbscences_$(Build.BuildId)

trigger:
  branches:
    include: [main, master]

schedules:
-
  cron: '0 1 * * *'
  displayName: 'Daily 1am run of PersonioAbscences'
  branches:
    include: [ main ]
  always: true

stages:
-
  stage: run
  displayName: Run Personio Abscence Notifier
  condition: ne(variables['Build.Reason'], 'PullRequest')
  pool:
    vmImage: ubuntu-latest
  jobs:
  -
    job: run
    steps:
    -
      task: GoTool@0
      inputs:
        version: '1.22.6'
      displayName: "Install Go"
    -
      task: DownloadSecureFile@1
      name: config
      inputs:
        secureFile: personio_notifier.yml
      displayName: "Download config file"
    -
      script: |
        go run ./cmd/... -config=$(config.secureFilePath)
      displayName: 'Run notifier'
